# Build

name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    name: R ${{ matrix.config.r }} | ${{ matrix.config.os }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - {os: ubuntu-latest,  r: 'release'}
          - {os: ubuntu-latest,  r: 'devel'}
    steps:
      - uses: actions/checkout@v2
      #OGC WFS/WMS integration tests
      #-------------------------
      #Docker Geoserver set-up
      - name: Set up GeoServer (latest)
        run: |
          docker pull kartoza/postgis
          docker run -d --name="postgis" kartoza/postgis
          docker run --link postgis:postgis -d -p 8080:8080 -e SAMPLE_DATA=true -e STABLE_EXTENSIONS=wps-plugin kartoza/geoserver:latest
      #OGC CSW integration tests
      #-------------------------
      #Docker PyCSW set-up
      - name: Set up PyCSW (latest)
        run: |
          docker pull geopython/pycsw:latest
          docker run --name pycsw -v $GITHUB_WORKSPACE/tests/pycsw/pycsw.cfg:/etc/pycsw/pycsw.cfg -d -p 8000:8000 geopython/pycsw:2.6.1
      #Docker GeoNetwork set-up
      #- name: Set up GeoNetwork (latest)
      #  run: |
      #    docker network create elasticnetwork
      #    docker run -d --name elasticsearch --net elasticnetwork --add-host host.docker.internal:host-gateway -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" elasticsearch:7.9.2
      #    docker run --add-host host.docker.internal:host-gateway -e ES_HOST=host.docker.internal --net elasticnetwork --name geonetwork -d -p 8080:8080 geonetwork
      #R tests
      #--------------------------
      #R Set-up
      - name: Set up R ${{ matrix.config.r }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
      #Install dependencies
      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck, any::XML
          needs: check
          cache-version: 5
          
      #Check R Package
      - name: Check R package
        uses: r-lib/actions/check-r-package@v2
        with:
          artifact-name: ows4R_r-${{ matrix.config.r }}_${{ matrix.config.os }}-results
